title: "VFG-VLA" 
description: >-
  Demonstration of Experiment Results for Virtual Penetration as a Force Proxy: Generating Synergistic Force-Aware Trajectories for Dual-Arm Manipulation.
baseurl: ""
url: "https://Submission-Documents.github.io"
theme: minima
paginate: 5

