title: "Contact"
email: xxx@example.com
description: >- # this means to fold newlines to spaces
  Demonstration of Experiment Results.
baseurl: "" # no leading slash for user site
url: "https://your-username.github.io"
theme: minima
paginate: 5
